version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --workers=4 --task-workers=2

  web:
    image: nginx
    container_name: laravel_web
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8084:80"
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    #restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel


  emqx:
    image: emqx/emqx:5.8.6
    container_name: laravel_emqx
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.io
      - EMQX_LISTENERS__TCP__DEFAULT__BIND=0.0.0.0:1883
      - EMQX_LISTENERS__SSL__DEFAULT__BIND=0.0.0.0:8883
      - EMQX_LISTENERS__WS__DEFAULT__BIND=0.0.0.0:8083
      - EMQX_DASHBOARD__LISTENERS__HTTP__BIND=0.0.0.0:18083
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_AUTHENTICATION__1__MECHANISM=password_based
      - EMQX_AUTHENTICATION__1__BACKEND=built_in_database
      - EMQX_AUTHENTICATION__1__ENABLE=true
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    networks:
      - laravel
    depends_on:
      - db
networks:
  laravel:

volumes:
  db_data:
  emqx_data:
  emqx_log: